# Generated by Django 5.2.1 on 2025-09-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_employer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_seeker',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seeker', 'Job Seeker'), ('employer', 'Employer'), ('admin', 'Admin')], default='seeker', max_length=20),
        ),
    ]
